version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.12.6
        environment:
          GO111MODULE: "on"

    working_directory: /go/src/github.com/woremacx/flac

    steps:
      - checkout

      - restore_cache:
          name: Restore go modules cache
          keys:
            - v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}

      - run: go test -v ./...

      - save_cache:
          name: Save go modules cache
          key: v1-mod-{{ .Branch }}-{{ checksum "go/go.mod" }}
          paths:
            - ~/go/pkg/mod/cache
